# Generated by Django 5.1.3 on 2025-11-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_domain_tenant_delete_client_delete_domain"),
        ("api", "0002_stationmodel_chargermodel_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="station",
            field=models.ForeignKey(
                blank=True,
                help_text="Hodim biriktirilgan station (Faqat hodimlar uchun)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="api.stationmodel",
                verbose_name="Station",
            ),
        ),
    ]
