# Generated by Django 5.2.7 on 2025-10-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(verbose_name='name')),
                ('cp_id', models.PositiveBigIntegerField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'StationModel',
                'verbose_name_plural': 'StationModels',
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='ConnectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conn_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='name')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Preparing', 'Preparing'), ('Charging', 'Charging'), ('SuspendedEV', 'Suspended EV'), ('SuspendedEVSE', 'Suspended EVSE'), ('Finishing', 'Finishing'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], default='SuspendedEV', verbose_name='status')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='api.stationmodel')),
            ],
            options={
                'verbose_name': 'ConnectorModel',
                'verbose_name_plural': 'ConnectorModels',
                'db_table': 'connector',
            },
        ),
    ]
