# Generated by Django 5.2.7 on 2025-11-07 12:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(verbose_name='name')),
                ('cp_id', models.PositiveBigIntegerField(unique=True, verbose_name='CpId')),
                ('last_health', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ChargerModel',
                'verbose_name_plural': 'ChargerModels',
                'db_table': 'charger',
            },
        ),
        migrations.CreateModel(
            name='ConnectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conn_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='name')),
                ('power', models.CharField(default=0, verbose_name='Power (Wh)')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Preparing', 'Preparing'), ('Charging', 'Charging'), ('SuspendedEV', 'Suspended EV'), ('SuspendedEVSE', 'Suspended EVSE'), ('Finishing', 'Finishing'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], default='SuspendedEV', verbose_name='status')),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='api.chargermodel')),
            ],
            options={
                'verbose_name': 'ConnectorModel',
                'verbose_name_plural': 'ConnectorModels',
                'db_table': 'connector',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(null=True, verbose_name='idTag')),
                ('status', models.CharField(choices=[('charging', 'Charging'), ('fail', 'Fail'), ('complate', 'Complate'), ('stop', 'Stop'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('soc', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='SoC (percent)')),
                ('is_active', models.BooleanField(default=True)),
                ('meter_start', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20)),
                ('meter_stop', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20)),
                ('meter_consumed', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20, verbose_name='Meter consumed (Wh)')),
                ('last_meter', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Last meter (Wh)')),
                ('is_force_stop', models.BooleanField(default=False, verbose_name='IS Force stop')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.connectormodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TransactionModel',
                'verbose_name_plural': 'TransactionModels',
                'db_table': 'transaction',
            },
        ),
    ]
