# Generated by Django 5.2.7 on 2025-10-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectormodel',
            name='power',
            field=models.CharField(default=0, verbose_name='Power (Wh)'),
        ),
    ]
