# Generated by Django 5.2.7 on 2025-10-30 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField(default=0)),
                ('energy', models.DecimalField(decimal_places=5, default=0.0, max_digits=5)),
                ('limit', models.DecimalField(decimal_places=2, default=-1.0, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('conn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connectormodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TransactionModel',
                'verbose_name_plural': 'TransactionModels',
                'db_table': 'transaction',
            },
        ),
    ]
