# Generated by Django 5.2.7 on 2025-11-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stationmodel_chargermodel_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargermodel',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='api.stationmodel'),
        ),
    ]
