# Generated by Django 5.2.7 on 2025-10-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_connectormodel_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
