# Generated by Django 5.2.7 on 2025-10-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transactionmodel_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='conn_id',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='conn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.connectormodel'),
        ),
    ]
