# Generated by Django 5.2.7 on 2025-10-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transactionmodel_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
