# Generated by Django 5.2.7 on 2025-10-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_transactionmodel_conn_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='conn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connectormodel'),
        ),
    ]
