# Generated by Django 5.2.7 on 2025-10-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transactionmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargermodel',
            name='last_health',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
