# Generated by Django 5.2.7 on 2025-10-31 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chargermodel_last_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='last_meter',
            field=models.BigIntegerField(default=0, verbose_name='Last meter (Wh)'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='conn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.connectormodel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='meter_consumed',
            field=models.BigIntegerField(default=0, verbose_name='Meter consumed (Wh)'),
        ),
    ]
