# Generated by Django 5.2.7 on 2025-10-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transactionmodel_conn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('charging', 'Charging'), ('fail', 'Fail'), ('complate', 'Complate'), ('stop', 'Stop'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
