# Generated by Django 5.2.7 on 2025-10-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_transactionmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='tag',
            field=models.CharField(null=True, verbose_name='idTag'),
        ),
    ]
