# Generated by Django 5.2.7 on 2025-11-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transactionmodel_last_meter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargermodel',
            name='cp_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='CpId'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='last_meter',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Last meter (Wh)'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='meter_consumed',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='Meter consumed (Wh)'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='meter_start',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='meter_stop',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
