# Generated by Django 5.2.7 on 2025-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chargermodel_cp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='is_force_stop',
            field=models.BooleanField(default=False, verbose_name='IS Force stop'),
        ),
    ]
