# Generated by Django 5.2.7 on 2025-10-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transactionmodel_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='meter_start',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='meter_stop',
            field=models.BigIntegerField(default=0),
        ),
    ]
