# Generated by Django 5.2.7 on 2025-10-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transactionmodel_meter_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='meter_consumed',
            field=models.BigIntegerField(default=0),
        ),
    ]
