# Generated by Django 5.2.7 on 2025-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transactionmodel_is_force_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
