# Generated by Django 5.2.7 on 2025-10-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transactionmodel_meter_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='energy',
        ),
    ]
