# Generated by Django 5.2.7 on 2025-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_transactionmodel_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='meter_consumed',
            field=models.BigIntegerField(default=0, verbose_name='Meter consumed Wh'),
        ),
    ]
