# Generated by Django 5.2.7 on 2025-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_transactionmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='soc',
            field=models.SmallIntegerField(default=0, verbose_name='SoC (percent)'),
        ),
    ]
