# Generated by Django 5.2.7 on 2025-10-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transactionmodel_soc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='soc',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='SoC (percent)'),
        ),
    ]
